<#PSScriptInfo
.VERSION 1.0.0
.GUID 0ed65ef9-0f8f-43d3-9fdd-b778072c08f0
.AUTHOR Synopsys
#>

using module @{ModuleName='guided-setup'; RequiredVersion='1.16.0' }
param (
	[Parameter(Mandatory=$true)][string] $configPath,
	[string] $configFilePwd
)

$ErrorActionPreference = 'Stop'
$VerbosePreference = 'Continue'

Set-PSDebug -Strict

Write-Host 'Loading...' -NoNewline

'../../keyvalue.ps1',
'../../config.ps1',
'../../build/protect.ps1',
'../../steps/step.ps1',
'../../steps/database.ps1',
'../../steps/finish.ps1',
'../../steps/pwd.ps1' | ForEach-Object {
	Write-Debug "'$PSCommandPath' is including file '$_'"
	$path = Join-Path $PSScriptRoot $_
	if (-not (Test-Path $path)) {
		Write-Error "Unable to find file script dependency at $path. Please download the entire srm-k8s GitHub repository and rerun the downloaded copy of this script."
	}
	. $path | out-null
}

if (-not (Test-Path $configPath -PathType Leaf)) {
	Write-Error "Unable to find configuration file named '$configPath'"
}

$config = [Config]::FromJsonFile($configPath)

$workDirectory = $config.workDir
$configDirectory = Split-Path (Resolve-Path $configPath)

# use GetFullPath to normalize directory separators (e.g., convert C:\Users\user/.k8s-srm to C:\Users\user\.k8s-srm)
$workDirectoryFullName   = [IO.Path]::GetFullPath($workDirectory)
$configDirectoryFullName = [IO.Path]::GetFullPath($configDirectory)
$isConfigInWorkDirectory = $workDirectoryFullName -eq $configDirectoryFullName

if (-not $isConfigInWorkDirectory) {
	# wizard writes the updated config.json to the work directory
	Write-Error "Unable to continue because your config.json file must reside in your work directory. Move your config.json file from '$configDirectoryFullName' to '$workDirectoryFullName' before retrying."
}

if ($config.isLocked) {

	if ([string]::IsNullOrEmpty($configFilePwd)) {
		$configFilePwd = Read-HostSecureText -Prompt 'Enter config file password'
	}

	$config.Unlock($configFilePwd)
}

# make a backup copy of the config file
Copy-Item $configPath ([IO.Path]::ChangeExtension($configPath, '.json.bak')) -Force

$graph = New-Object Graph($true)

$s = @{}
[WelcomePasswords],
[AbortPasswords],
[ResetAdminPassword],
[DatabaseUserPwd],
[DatabaseReplicationPwd],
[DatabaseRootPwd],
[ExternalDatabasePwd],
[Lock],
[MinioAdminPassword],
[PwdProcedureOverview],
[PwdProcedureWrapUp],
[ResetExternalDatabaseProcedure],
[ResetMasterDBPwdProcedure],
[ResetMinIOPwdProcedure],
[ResetReplicaDBPwdProcedure],
[ResetToolServiceKeyProcedure],
[ResetWebPwdProcedure],
[ToolServiceKey],
[UseAutoGeneratedPwds],
[Finish] | ForEach-Object {
	Write-Debug "Creating $_ object..."
	$s[$_] = new-object -type $_ -args $config
	Add-Step $graph $s[$_]
}

Add-StepTransitions $graph $s[[WelcomePasswords]] $s[[UseAutoGeneratedPwds]],$s[[AbortPasswords]]
Add-StepTransitions $graph $s[[WelcomePasswords]] $s[[UseAutoGeneratedPwds]],$s[[ResetAdminPassword]]
Add-StepTransitions $graph $s[[WelcomePasswords]] $s[[ResetAdminPassword]]

Add-StepTransitions $graph $s[[ResetAdminPassword]] $s[[ExternalDatabasePwd]],$s[[ToolServiceKey]]
Add-StepTransitions $graph $s[[ResetAdminPassword]] $s[[ExternalDatabasePwd]],$s[[Lock]]

Add-StepTransitions $graph $s[[ResetAdminPassword]] $s[[DatabaseUserPwd]],$s[[DatabaseRootPwd]],$s[[DatabaseReplicationPwd]],$s[[ToolServiceKey]]
Add-StepTransitions $graph $s[[ResetAdminPassword]] $s[[DatabaseUserPwd]],$s[[DatabaseRootPwd]],$s[[ToolServiceKey]]

Add-StepTransitions $graph $s[[DatabaseRootPwd]] $s[[Lock]]
Add-StepTransitions $graph $s[[DatabaseRootPwd]] $s[[DatabaseReplicationPwd]],$s[[Lock]]

Add-StepTransitions $graph $s[[ToolServiceKey]] $s[[MinioAdminPassword]],$s[[Lock]]
Add-StepTransitions $graph $s[[ToolServiceKey]] $s[[Lock]]

Add-StepTransitions $graph $s[[Lock]] $s[[PwdProcedureOverview]],$s[[ResetWebPwdProcedure]],$s[[ResetExternalDatabaseProcedure]],$s[[ResetToolServiceKeyProcedure]]
Add-StepTransitions $graph $s[[Lock]] $s[[PwdProcedureOverview]],$s[[ResetWebPwdProcedure]],$s[[ResetReplicaDBPwdProcedure]],$s[[ResetMasterDBPwdProcedure]],$s[[ResetToolServiceKeyProcedure]],$s[[ResetMinIOPwdProcedure]],$s[[PwdProcedureWrapUp]]
Add-StepTransitions $graph $s[[PwdProcedureOverview]] $s[[ResetWebPwdProcedure]],$s[[ResetMasterDBPwdProcedure]]
Add-StepTransitions $graph $s[[ResetMasterDBPwdProcedure]] $s[[PwdProcedureWrapUp]]
Add-StepTransitions $graph $s[[ResetToolServiceKeyProcedure]] $s[[PwdProcedureWrapUp]]
Add-StepTransitions $graph $s[[ResetExternalDatabaseProcedure]] $s[[PwdProcedureWrapUp]]

Add-StepTransitions $graph $s[[PwdProcedureWrapUp]] $s[[Finish]]

if ($DebugPreference -eq 'Continue') {
	# Print graph at https://dreampuf.github.io/GraphvizOnline (select 'dot' Engine and use Format 'png-image-element')
	write-host 'digraph G {'
	$s.keys | ForEach-Object { $node = $s[$_]; ($node.getNeighbors() | ForEach-Object { write-host ('{0} -> {1};' -f $node.name,$_) }) }
	write-host '}'
}

try {
	$vStack = Invoke-GuidedSetup 'SRM - Set Passwords Wizard' $s[[WelcomePasswords]] ($s[[Finish]],$s[[AbortPasswords]])
	Write-StepGraph (Join-Path ($config.workDir ?? './') 'graph.wiz.pwd.path') $s $vStack
} catch {
	Write-Host "`n`nAn unexpected error occurred: $_`n"
	Write-Host $_.ScriptStackTrace
}
