{{- if .Values.openshift.createSCC -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "srm-web.scc" . }}
allowPrivilegeEscalation: false
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 1000
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAs
  uid: 1000
seccompProfiles:
- runtime/default
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "srm-web.serviceAccountName" . }}
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
{{ if .Values.features.mariadb -}}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "srm-web.database.scc" . }}
allowPrivilegeEscalation: false
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1001
    max: 1001
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAs
  uid: 1001
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "srm-web.database.serviceAccountName" . }}
volumes:
- configMap
- persistentVolumeClaim
- secret
{{- end }}
{{- end -}}