{{- if and .Values.features.to .Values.openshift.createSCC -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "srm-to.scc" . }}
allowPrivilegeEscalation: false
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 1000
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAs
  uid: 1000
seccompProfiles:
- runtime/default
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "srm-to.serviceAccountName" . }}
volumes:
- configMap
- emptyDir
- secret
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "srm-workflow-controller.scc" . }}
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAs
  uid: 1000
seccompProfiles:
- runtime/default
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "argo-workflows.ref.controllerServiceAccountName" . }}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "srm-to.workflow-scc" . }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- SYS_PTRACE
- SYS_CHROOT
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "srm-to.serviceAccountNameWorkflow" . }}
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
- downwardAPI
{{- end -}}
